data_path: 'datasets/Mixed'
save_path: 'outputs'
# labels: ['Sad', 'Happy', 'Angry', 'Neutral', 'Surprise']

audio_model:
  ckpt: 'facebook/wav2vec2-base-960h'
  pooling_mode: 'mean'

language_model:
  ckpt: 'bert-base-uncased'
hidden_size: 768
projection_size: 256

dist_config:
  dist_backend: 'nccl'
  dist_url: 'tcp://172.18.240.231:3060'
  world_size: 1

train:
  batch_size: 16
  device_ids: [1]
  dropout: 0.1
  gradient_accumulation: 1
  learning_rate: 5.0E-7
  lr_decay_step: 1
  lr_decay_rate: 0.1
  temperature: 1.0
  total_step: 20000
  log_step: 50
  eval_step: 500
  save_step: 5000

test:
  batch_size: 16